version: "3.8"
services:
  server:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      DATABASE_URL: mongodb://mongo/boiler
  mongo:
    image: mongo:5-focal
    ports:
      - 27017:27017
    volumes: 
      - data:/data/db

volumes:
  data:
